name: Sync

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Sync to public repo
      if: github.repository == 'BugSwarm/test-mirror-private'
      uses: BugSwarm/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source-repo: 'git@github.com:BugSwarm/test-mirror-private.git'
        destination-repo: 'git@github.com:BugSwarm/test-mirror-public.git'
    - name: Sync to private repo
      if: github.repository == 'BugSwarm/test-mirror-public'
      uses: BugSwarm/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source-repo: 'git@github.com:BugSwarm/test-mirror-public.git'
        destination-repo: 'git@github.com:BugSwarm/test-mirror-private.git'

