name: Sync

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure user
      run: |
        git config --global user.email 'pcding@ucdavis.edu'
        git config --global user.name 'Pengcheng Ding'

    - name: Push to public repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TEST_TOKEN }}
        repository: 'BugSwarm/test-mirror-public'
