name: Sync

on:
  push:
    branches:
      - master

env:
  PRIVATE_REPO: 'BugSwarm/test-mirror-private'
  PUBLIC_REPO: 'BugSwarm/test-mirror-public'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Sync to public repo
      if: github.repository == env.PRIVATE_REPO
      uses: BugSwarm/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source-repo: ${{ env.PRIVATE_REPO }}
        destination-repo: ${{ env.PUBLIC_REPO }}

    - name: Sync to private repo
      if: github.repository == env.PUBLIC_REPO
      uses: BugSwarm/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source-repo: ${{ env.PUBLIC_REPO }}
        destination-repo: ${{ env.PRIVATE_REPO }}

