name: Sync

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Publish repo
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source-repo: 'git@github.com:BugSwarm/test-mirror-private.git'
        destination-repo: 'git@github.com:BugSwarm/test-mirror-public.git'
