name: Sync

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Push to public repo
      run: git push --prune git@github.com:BugSwarm/test-mirror-public.git
